In [13]:
import cv2
import numpy as np

In [14]:
image = cv2.imread("Lucy.jpg")
print(image)

[[[136 155 198]
  [136 155 198]
  [136 155 198]
  ...
  [163 177 183]
  [163 177 183]
  [163 177 183]]

 [[136 155 198]
  [136 155 198]
  [136 155 198]
  ...
  [159 173 179]
  [159 173 179]
  [159 173 179]]

 [[136 155 198]
  [136 155 198]
  [136 155 198]
  ...
  [157 171 177]
  [157 171 177]
  [157 171 177]]

 ...

 [[  4   0   0]
  [  5   0   1]
  [  6   1   2]
  ...
  [ 74  73 112]
  [ 73  72 111]
  [ 72  71 110]]

 [[  4   0   0]
  [  6   1   2]
  [  8   3   4]
  ...
  [ 72  71 110]
  [ 71  70 109]
  [ 71  70 109]]

 [[  4   0   0]
  [  4   0   0]
  [  4   0   0]
  ...
  [ 74  73 112]
  [ 74  73 112]
  [ 73  72 111]]]


In [15]:
image.shape

(1625, 2268, 3)

In [16]:
cv2.imshow("cat", image)
cv2.waitKey(0)

-1

RGB (0, 1, 2)

In [19]:
green_image=image[:,:,1]

In [18]:
cv2.imshow("greencat", green_image)
cv2.waitKey(0)

-1

In [20]:
cv2.imwrite("lucy_green.jpg", green_image)

True

In [24]:
cv2.destroyAllWindows()