# NumPy 


To get started we need to install it!

pip install numpy

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [2]:
import numpy as np

Some of the most important components of Numpy: vectors,arrays,matrices, and number generation.

# Numpy Arrays

Numpy arrays: vectors and matrices.


In [3]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [6]:
np.array(my_list)
my_list

[1, 2, 3]

In [7]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,11,3)

array([0, 3, 6, 9])

### zeros and ones

Generate arrays of zeros or ones

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones(3)

array([1., 1., 1.])

In [16]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [17]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [18]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [20]:
np.random.rand(2)

array([0.55998765, 0.61331071])

In [21]:
np.random.rand(5,5)

array([[0.75982619, 0.56881616, 0.71886993, 0.72051367, 0.26968393],
       [0.62423497, 0.56542365, 0.23917991, 0.29587798, 0.02146996],
       [0.20530407, 0.63278651, 0.5024663 , 0.6097843 , 0.83135642],
       [0.16810485, 0.04470814, 0.30338217, 0.07164473, 0.42024895],
       [0.18867354, 0.51822704, 0.50517743, 0.79771541, 0.70950597]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [22]:
np.random.randn(2)

array([ 0.35770459, -0.22046965])

In [23]:
np.random.randn(5,5)

array([[ 0.04784671, -0.19169497,  1.28112949,  0.00846819, -0.39306581],
       [-0.73206631, -0.94073923,  0.09326176,  0.80956654,  1.06762309],
       [-2.07447017,  0.50788765, -0.75476859, -0.98750564, -0.02107143],
       [ 0.42892142,  0.33694785,  0.25667243,  1.87047559, -0.72882672],
       [-0.65640414,  0.22048004,  0.36480872, -0.76784005,  2.27052584]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [24]:
np.random.randint(1,100)

42

In [25]:
np.random.randint(1,100,10)

array([52, 87, 96, 79, 87, 50, 63, 38, 83, 89], dtype=int32)

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [26]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
ranarr

array([25, 10, 37,  3, 36, 17,  9,  8,  6, 12], dtype=int32)

## Reshape
Returns an array containing the same data with a new shape.

In [29]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [30]:
ranarr

array([25, 10, 37,  3, 36, 17,  9,  8,  6, 12], dtype=int32)

In [31]:
ranarr.max()

np.int32(37)

In [33]:
ranarr.argmax()

np.int64(2)

In [34]:
ranarr.min()

np.int32(3)

In [35]:
ranarr.argmin()

np.int64(3)

## Shape

Shape is an attribute that arrays have (not a method):

In [36]:
# Vector
arr.shape

(25,)

In [37]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [38]:
arr.reshape(1,25).shape

(1, 25)

In [39]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [40]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [41]:
arr.dtype

dtype('int64')

# Great Job!