# NumPy Exercises 


#### Import NumPy as np

In [2]:
import numpy as np

#### Create an array of 10 zeros 

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [7]:
my_list = [5,5,5,5,5,5,5,5,5,5]
np.array(my_list)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### Create an array of the integers from 10 to 50

In [8]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [9]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [10]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Use NumPy to generate a random number between 0 and 1

In [17]:
np.random.rand(1)

array([0.30105684])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [18]:
np.random.randn(25)

array([ 0.03061754,  0.40710061,  1.757396  , -0.05246815, -1.17919574,
       -0.15534636, -1.1457046 ,  2.30922807,  0.98713996,  0.98830743,
        0.18940093, -0.0804185 , -0.55656721,  0.86518782, -0.17413652,
        0.18287798,  0.5108017 , -0.56595878,  2.51391079,  1.08469943,
        0.83574846, -0.45642142, -1.08824906, -0.40782413,  1.07957508])

#### Create the following matrix:

#### Create an array of 20 linearly spaced points between 0 and 1:

In [21]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [25]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

**Write a code that creates the following output**

In [28]:
mat[[2,3,4]]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [29]:
mat[3,4]

np.int64(20)

In [41]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [42]:
mat[4]

array([21, 22, 23, 24, 25])

In [43]:
mat[[3,4]]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [44]:
np.sum(mat)

np.int64(325)

#### Get the sum of all the columns in mat

In [45]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

# Great Job!